name: Get Changed Files

on:
  push:
    branches:
      - main

jobs:
  get_changed_files:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Get changed files
        id: changed_files
        run: |
          git fetch --prune --unshallow
          changed_files=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})
          echo "::set-output name=changed_files::$changed_files"

      - name: Print changed files
        run: echo "Changed files: ${{ steps.changed_files.outputs.changed_files }}"
